services:
  - type: web
    name: streamlit-test-app # Puedes cambiar este nombre si quieres
    env: python
    buildCommand: pip install -r requirements.txt --no-cache-dir
    startCommand: python -m streamlit run app.py --server.port $PORT
    pythonVersion: 3.9.23 # Asegúrate de que esta coincida con tu .python-version
    plan: free # Puedes usar 'starter' o 'free'